git clone https://github.com/Geeksltd/Zebble.WebApi/
git clone https://github.com/Geeksltd/Zebble.Vibration/
git clone https://github.com/Geeksltd/Zebble.Video/
git clone https://github.com/Geeksltd/Zebble.VideoPlayer/
git clone https://github.com/Geeksltd/Zebble.Torch/
git clone https://github.com/Geeksltd/Zebble.Switch/
git clone https://github.com/Geeksltd/Zebble.Speech/
git clone https://github.com/Geeksltd/Zebble.SpannableTextView/
git clone https://github.com/Geeksltd/Zebble.SmoothCompass/
git clone https://github.com/Geeksltd/Zebble.Slider/
git clone https://github.com/Geeksltd/Zebble.SignaturePad/
git clone https://github.com/Geeksltd/Zebble.Sharing/
git clone https://github.com/Geeksltd/Zebble.Sensors/
git clone https://github.com/Geeksltd/Zebble.SegmentedViews/
git clone https://github.com/Geeksltd/Zebble.SearchInput/
git clone https://github.com/Geeksltd/Zebble.RecyclerView/
git clone https://github.com/Geeksltd/Zebble.PushNotification/
git clone https://github.com/Geeksltd/Zebble.Printing/
git clone https://github.com/Geeksltd/Zebble.PopOver/
git clone https://github.com/Geeksltd/Zebble.OxyPlot/
git clone https://github.com/Geeksltd/Zebble.OptionsList/
git clone https://github.com/Geeksltd/Zebble.OpenTok/
git clone https://github.com/Geeksltd/Zebble.Office365/
git clone https://github.com/Geeksltd/Zebble.OAuth/
git clone https://github.com/Geeksltd/Zebble.NavBarTabs/
git clone https://github.com/Geeksltd/Zebble.Messaging/
git clone https://github.com/Geeksltd/Zebble.Media/
git clone https://github.com/Geeksltd/Zebble.MapBox/
git clone https://github.com/Geeksltd/Zebble.Map/
git clone https://github.com/Geeksltd/Zebble.Lottie/
git clone https://github.com/Geeksltd/Zebble.AppLinks/
git clone https://github.com/Geeksltd/Zebble.Audio/
git clone https://github.com/Geeksltd/Zebble.AugmentedReality/
git clone https://github.com/Geeksltd/Zebble.BarcodeScanner/
git clone https://github.com/Geeksltd/Zebble.BoxShadow/
git clone https://github.com/Geeksltd/Zebble.Calendar/
git clone https://github.com/Geeksltd/Zebble.CameraView/
git clone https://github.com/Geeksltd/Zebble.Carousel/
git clone https://github.com/Geeksltd/Zebble.CheckBox/
git clone https://github.com/Geeksltd/Zebble.CoachMarks/
git clone https://github.com/Geeksltd/Zebble.Contacts/
git clone https://github.com/Geeksltd/Zebble.Data/
git clone https://github.com/Geeksltd/Zebble.DateTimePicker/
git clone https://github.com/Geeksltd/Zebble.Drawing/
git clone https://github.com/Geeksltd/Zebble.Facebook/
git clone https://github.com/Geeksltd/Zebble.FilePicker/
git clone https://github.com/Geeksltd/Zebble.Fingerprint/
git clone https://github.com/Geeksltd/Zebble.FloatingButton/
git clone https://github.com/Geeksltd/Zebble.Google/
git clone https://github.com/Geeksltd/Zebble.IconButton/
git clone https://github.com/Geeksltd/Zebble.Inspector/
git clone https://github.com/Geeksltd/Zebble.InteractiveCanvas/
git clone https://github.com/Geeksltd/Zebble.ItemPicker/
git clone https://github.com/Geeksltd/Zebble.ListView/
git clone https://github.com/Geeksltd/Zebble.LocalNotification/
git clone https://github.com/Geeksltd/Zebble.Location/
